export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const BARS_NEAR_ME_REQUEST = 'BARS_NEAR_ME_REQUEST';
export const BARS_NEAR_ME_SUCCESS = 'BARS_NEAR_ME_SUCCESS';
export const BARS_NEAR_ME_ERROR = 'BARS_NEAR_ME_ERROR';

export const BARS_NEAR_LOC_REQUEST = 'BARS_NEAR_LOC_REQUEST';
export const BARS_NEAR_LOC_SUCCESS = 'BARS_NEAR_LOC_SUCCESS';
export const BARS_NEAR_LOC_ERROR = 'BARS_NEAR_LOC_ERROR';

export const BARS_GOING_TO_REQUEST = 'BARS_GOING_TO_REQUEST';
export const BARS_GOING_TO_SUCCESS = 'BARS_GOING_TO_SUCCESS';
export const BARS_GOING_TO_ERROR = 'BARS_GOING_TO_ERROR';

export const GOING_TO_BAR_REQUEST = 'GOING_TO_BAR_REQUEST';
export const GOING_TO_BAR_SUCCESS = 'GOING_TO_BAR_SUCCESS';
export const GOING_TO_BAR_ERROR = 'GOING_TO_BAR_ERROR';

export const NOT_GOING_TO_BAR_REQUEST = 'NOT_GOING_TO_BAR_REQUEST';
export const NOT_GOING_TO_BAR_SUCCESS = 'NOT_GOING_TO_BAR_SUCCESS';
export const NOT_GOING_TO_BAR_ERROR = 'NOT_GOING_TO_BAR_ERROR';
